kind: pipeline
name: greeting

steps:
- name: en
  image: alpine
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  settings:
    repo: octocat/server
    tags: latest
    username:
      from_secret: username
    password:
      from_secret: password
  commands:
  - echo $USERNAME
  - echo $${USERNAME}

---
kind: secret

external_data:
  username:
    path: secret/data/docker
    name: username
  password:
    path: secret/data/docker
    name: password
