kind: pipeline
name: default

steps:
  - name: test
    image: microadam/drone-osx-runner
    environment:
      MY_ENV: "Hello"
    settings:
      host: 'http://microadam.co.uk:3000'
      key: 'abc123'
      inputContext:
        - .
      commands:
        - echo $MY_ENV
        - echo $DRONE_COMMIT

trigger:
  changeset:
    includes: [ '**' ]
  event:
    exclude:
    - pull_request

---
kind: secret

external_data:
  github_token:
    name: githubToken
