kind: pipeline
name: default

steps:
  - name: test
    image: alpine
    commands:
      - echo "YML OR A CHANGED"
    when:
      changeset:
        includes: [ '*' ]

trigger:
  changeset:
    includes: [ 'a/**' ]
