kind: pipeline
name: greeting

steps:
- name: en
  image: eu.gcr.io/test-k8s-1289/clock-node:8.11.3-build
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
  - echo hello
  - echo world

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde

