kind: pipeline
name: default

steps:
  - name: always
    image: alpine
    commands:
      - echo "ALWAYS"

  - name: test
    image: alpine
    commands:
      - echo "YML OR A CHANGED"
    when:
      changeset:
        includes: [ '**' ]

trigger:
  changeset:
    includes: [ '**', '.drone.yml' ]
