kind: pipeline
name: greeting

steps:
- name: en
  image: alpine
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
    MYSECRET:
      from_secret: MYSECRET
  settings:
    repo: octocat/server
    tags: latest
    username:
      from_secret: username
    password:
      from_secret: password
  commands:
  - export
  - echo "$USERNAME"
  - echo "$${USERNAME}"

---
kind: secret

external_data:
  username:
    path: secret/data/docker
    name: username
  password:
    path: secret/data/docker
    name: password
